---
interfaces:
    interface:
        _block_capture: "(?P<block>interface (?P<key>(Ethernet|Management|Loopback|Port-Channel)\\d+)\n(?:.|\n)*?^!$)"
        name:
            _search: "interface (?P<value>(Ethernet|Management|Loopback|Port-Channel).*)"
            _type: py23_compat.text_type
        hold_time:
            config:
                down:
                    _search: "napalm: not implemented"
                    _type: int
                    _default: 0
                up:
                    _search: "napalm: not implemented"
                    _type: int
                    _default: 0
        config:
            name:
                _search: "interface (?P<value>(Ethernet|Management|Loopback|Port-Channel).*)"
                _type: py23_compat.text_type
            type_:
                _search: "interface (?P<value>(Ethernet|Management|Loopback|Port-Channel)).*"
                _type: mapping
                _map:
                    Ethernet: napalm_yang.ianaift.Ethernetcsmacd
                    Management: napalm_yang.ianaift.Ethernetcsmacd
                    Loopback: napalm_yang.ianaift.Softwareloopback
                    Port-Channel: napalm_yang.ianaift.Ieee8023Adlag
            enabled:
                _search: "no shutdown"
                _type: boolean
                _default: False
            description:
                _search: "description (?P<value>.*)"
                _type: py23_compat.text_type
                _default: ""
            mtu:
                _search: "mtu (?P<value>[0-9]+)"
                _type: int
                _default: 1500
        subinterfaces:
            subinterface:
                _block_capture: "(?P<block>interface (?P<key>{parent_key}\\.\\d+)\\n(?:.|\\n)*?^!$)"
                index:
                    _search: "napalm: not implemented"
                    _type: int
                    _default: 0
                config:
                    index:
                        _search: "napalm: not implemented"
                        _type: int
                        _default: 0
                    name:
                        _search: "interface (?P<value>Ethernet.*)"
                        _type: py23_compat.text_type
                    enabled:
                        _search: "no shutdown"
                        _type: boolean
                        _default: False
                    description:
                        _search: "description (?P<value>.*)"
                        _type: py23_compat.text_type
                        _default: ""
